---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Configure Nginx for load balancing
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: Reload Nginx

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Open HTTP port in firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

